// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © ZenAndTheArtOfTrading
// @version=5
strategy("s4 MA Crossover", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

// === BACKTEST RANGE ===
Start = input.time(defval = timestamp("01 Jan 2008 06:00 +0000"), title = "Backtest Start Date", group = "backtest window")
Finish = input.time(defval = timestamp("01 Jan 2024 00:00 +0000"), title = "Backtest End Date", group = "backtest window")

// Get user input
emaLength1 = input.int(title="EMA #1 Length", defval=50)
emaLength2 = input.int(title="EMA #2 Length", defval=100)

// Get MAs
ema1 = ta.ema(close, emaLength1)
ema2 = ta.ema(close, emaLength2)

// Draw MAs
plot(ema1, color=color.blue, title="EMA 1")
plot(ema2, color=color.red, title="EMA 2")

// Detect crossovers
bool crossOver = ta.crossover(ema1, ema2)
bool crossUnder = ta.crossunder(ema1, ema2)
bool cross = crossOver or crossUnder
//float crossPrice = ta.valuewhen(cross, close, 0)
float crossPrice = cross ? close : na

bool in_time_range=time<Finish and time>Start

inPosition = strategy.position_size > 0
bgcolor(inPosition?color.new(color.green,70):na)

if crossOver and in_time_range and strategy.position_size == 0
    strategy.entry(id="Buy", direction=strategy.long)
if crossUnder and in_time_range and strategy.position_size > 0
    strategy.close(id="Buy")

if time>=Finish and strategy.position_size > 0
    strategy.close('Buy')
